e-store/config/routes.rb
EStore::Application.routes.draw do

  

  get "login/register"

  post "login/create"

  post "login/validate_user"

  get "login/show_all"

  delete "login/delete"
  
  match "/login" => 'login#index'

  resources :provences


  resources :products


  resources :orders


  resources :lineitems


  resources :customers


  root :to => "products#index"
  
#  match "admin" => "active_admin/devise/sessions#new",:as => "admin"
  
  match "result" => "products#search", :as => "result", :via => :post
  
  match "add_product_to_cart" => "products#add_product_to_cart", :as => "add_product_to_cart", :via => :post
  
  match "remove_product_to_cart" => "products#remove_product_to_cart", :as => "remove_product_to_cart", :via => :post
  
  match "checkout" => "products#checkout", :as => "checkout", :via => :post
 # match "checkout" => "products#clear_cart", :as => "clear_cart", :via => :post
 
 # match "purchase" => "products#purchase", :as => "purchase", :via => :post
  match "purchase" => "products#purchase", :as => "purchase", :via => :get
  match "customers" => "customers#new", :as => "customers", :via => :get
  
  #match "customers/:id" => "products#purchase", :as => "purchase", :via => :get
  #match "customers" => "products#purchase", :as => "purchase", :via => :get
  
  
 # match "/customer" => "customers#index"
 # match "/order" => "orders#index"
 # match "/product" => "products"

devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
end

e-store/app/models/product.rb
class Product < ActiveRecord::Base
  attr_accessible :description, :image, :name, :price, :sale_price, :stock_quantity, :item
  
  validates :description, :name, :price, :stock_quantity, :item, :presence => true
  validates :name, :description, :uniqueness => true
  validates :price, :numericality => { :greater_than_or_equal_to => 0 }
  
  has_many :lineitems
  has_many :orders, :through => :lineitems
  
  def self.search(search)
    if search
      find(:all, :conditions => ['name LIKE ?', "%#{search}%"])
    else
      find(:all)
    end
  end
end

e-store/app/controllers/products_controller.rb
class ProductsController < ApplicationController
  # GET /products
  # GET /products.json
  def index
    @products = Product.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @products }
    end

    if session[:count].nil?
      session[:count] = 1
    else 
      session[:count] += 1
    end
    
    @count = session[:count]
  end
  
  def search
    @products = Product.search(params[:search])
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @product = Product.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/new
  # GET /products/new.json
  def new
    @product = Product.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/1/edit
  def edit
    @product = Product.find(params[:id])
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(params[:product])

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render json: @product, status: :created, location: @product }
      else
        format.html { render action: "new" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /products/1
  # PUT /products/1.json
  def update
    @product = Product.find(params[:id])

    respond_to do |format|
      if @product.update_attributes(params[:product])
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product = Product.find(params[:id])
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url }
      format.json { head :no_content }
    end
  end

  def search
    @keyword = params[:keyword]
    
    @products = Product.where("name LIKE ?", "%#{@keyword}%")
  end
  
  def add_product_to_cart
    ##empty array of cart if its null
    session[:cart] = []  if session[:cart].nil?
    
    ##if item exists in the cart we add qty and findflag true
    found_flag = false
    session[:cart].each do |item|
      if item.itemNo == params[:id]
        found_flag = true
        item.itemQty += params[:qty].to_i
      end
    end
    
    ##push the item into cart if not currently there
    session[:cart] << Cart_item.new(params[:id], params[:qty])  if found_flag == false
    
    redirect_to root_url
  end
  
  def remove_product_to_cart
    ##loop threw items in the cart
    session[:cart].each do |item|
      ##remove the item that matches selected request
      session[:cart].delete(item)  if item.itemNo == params[:id]
    end
    
    redirect_to root_url
  end
  
  def checkout
    ## tests the commit value for which checkout button was selected
    ## theres only Clear Cart! and Checkout!
    if params[:commit] == "Clear Cart!" then
      ##resets all the sessions on clear cart
      #session[:cart] = nil
      reset_session
    else
      ##we want to sumbit to our checkout page with summary
     # redirect_to purchase_url
     if not session[:cart] == []
       ##send customer to create a form with his info
      redirect_to new_customer_url and return
     end
    end
    redirect_to root_url
  end
  
end

e-store/app/helpers/products_helper.rb
module ProductsHelper
end

e-store/app/views/products/_cart.html.erb
<h1>Cart</h1>
<p>Product NO: <%= cart.itemNo %>
<br/>
Product QTY: <%= cart.itemQty %>
</p>

e-store/app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :price %><br />
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :stock_quantity %><br />
    <%= f.number_field :stock_quantity %>
  </div>
  <div class="field">
    <%= f.label :item %><br />
    <%= f.text_field :item %>
  </div>
  <div class="field">
    <%= f.label :sale_price %><br />
    <%= f.text_field :sale_price %>
  </div>
  <div class="field">
    <%= f.label :image %><br />
    <%= f.text_field :image %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

e-store/app/views/products/_product.html.erb
<div class="product">
  <span class="float-right">
    <%= link_to 'Inspect', product %> | 
    <%= link_to 'Edit', edit_product_path(product) %> |
    <%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %>
  </span>
  Score: ??
  <b class="name">Product: </b><%= product.name %>
  <b class="item"><%= product.item %></b><br/>
  <span class="product-icon"><%= image_tag(product.image, :size => "70x100") %></span>
  <b>Price: </b><%= number_to_currency(product.price) %><br/>
  <b> Stock: </b><%= number_with_delimiter(product.stock_quantity) %>
  
  
  <%= form_tag add_product_to_cart_path, :class => "form", :method => 'post' do %> 
    <%= submit_tag "ADD", :class => "add_btn"%>
    <%= text_field_tag(:qty, value = nil,
                                options = {:placeholder => "##",
                                           :class => "qty_box"})%>
    <%= hidden_field_tag(:id, product.id.to_s) %></br>
  <% end %>
  
  
  
  
  <% if product.sale_price > 0 then %>
      <b class="sale">*ON SALE* - Save: <%= product.sale_price %></b><br/>
    <% end %>
  <br/>
  <b>Description: </b> <%= product.description %>
</div>

e-store/app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

e-store/app/views/products/index.html.erb
<!--
<% @products.each do |product| %>
  <p class="product">
    <span class="float-right">
      <%= link_to 'Show', product %> | 
      <%= link_to 'Edit', edit_product_path(product) %> |
      <%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %>
    </span>
    Score: ??
    <b class="name">Product: </b><%= product.name %>
    <b class="item"><%= product.item %></b><br/>
    <span class="product-icon"><%= image_tag(product.image, :size => "70x100") %></span>
    <b>Price: </b><%= number_to_currency(product.price) %><br/>
    <b> Stock: </b><%= number_with_delimiter(product.stock_quantity) %>
    <%= button_tag "ADD", :class => "add_btn"%>
    <%= text_field_tag(:qty, value = nil,
                                options = {:placeholder => "##",
                                           :class => "qty_box"})%></br>
    <% if product.sale_price > 0 then %>
        <b class="sale">*ON SALE* - Save: <%= product.sale_price %></b><br/>
      <% end %>
    <br/>
    <b>Description: </b> <%= product.description %>
  </p>
<% end %>
-->
<%= render @products %>
<!--
<br/>
<%= link_to 'New Product', new_product_path %><br/>
<%= link_to 'Customers', customers_path %><br/> 
<%= link_to 'Orders', orders_path %><br/> 
<%= link_to 'Provences', provences_path %>
-->

e-store/app/views/products/new.html.erb
<h1>New product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

e-store/app/views/products/purchase.html.erb
<html>
	<body>
<!--	<% if session[:cart].empty? %>
	  <p id="error">Please purchase some products.</p>
	<% end %>
-->
		<h1>CHECK OUT!!</h1>
		<% customer = Customer.where(:id => session[:customer_id]).first %>
		<% items = [] %>
		<% session[:lineitem_ids].each do |item| %>
		<% items << Product.where(:id => item.to_i).first %>
		<% end %>
<!-- 	<%= debug session[:customer_id] %>
	<hr/>
	<%= debug session[:order_id] %>
	<hr/>
	<%= debug session[:lineitem_ids] %>
	<hr/> -->

		<div id="custInfo">			
			<p>
				<b><u>Customer Information:</u></b><br/>
				<%= customer.first_name %> <%= customer.last_name %><br/>
				<%= customer.address %> <br/>
				<%= customer.city %> <%= customer.provence.code %> <br/>
				<%= customer.postal_code %>
			</p>			
		</div>
		<hr/>
		<% total_sub_cost = 0.0 %>
		<% total_gst_cost = 0.0 %>
		<% total_pst_cost = 0.0 %>
		<% total_hst_cost = 0.0 %>
		<% grand_total_cost = 0.0 %>
		<div id="itemInfo">
			<b><u>Item Information:</u></b>
			<div id="small_item">
			<% session[:cart].each do |item| %>
				<% @product = Product.where(:id => "#{item.itemNo}").first %>
				<p><span class="float_left">
					<%= image_tag(@product.image, :size => "35x50") %></span>
					<%= @product.name %><br/>
					QTY: <%= item.itemQty %> <br/>
					Cost: <%= @product.price - @product.sale_price %>/ea.<br/>
					Sub total: $<%= ((@product.price - @product.sale_price) * item.itemQty.to_i) %>

					<% total_sub_cost += ((@product.price - @product.sale_price) * item.itemQty.to_i) %>
				</p>
			<% end %>
			</div>
		</div>
		<hr/>
		<% order = Order.where(:id => session[:order_id]).first %>
		<% total_pst_cost += customer.provence.pst * total_sub_cost %>
		<% total_gst_cost += customer.provence.gst * total_sub_cost %>
		<% total_hst_cost += customer.provence.hst * total_sub_cost %>

		<% grand_total_cost += (
			total_pst_cost + 
			total_gst_cost +
			total_hst_cost +
			total_sub_cost ) %>
		<div id="summary">
			<b><u>Final Cost Summary:</u></b>
			<p>
				Subtotal: <%= number_to_currency(total_sub_cost) %><br/>
				<% if total_pst_cost > 0 %>
				Total PST: <%= number_to_currency(total_pst_cost) %><br/>
				<% end %>
				<% if total_gst_cost > 0 %>
				Total GST: <%= number_to_currency(total_gst_cost) %><br/>
				<% end %>
				<% if total_hst_cost > 0 %>
				Total HST: <%= number_to_currency(total_hst_cost) %><br/>
				<% end %>
				Grand Total: <%= number_to_currency(grand_total_cost) %>
			</p>
		</div>
		<hr/>
		<div id="choices">
			<p>ACCEPT BTN (pay) | CANCEL BTN(clear session -> root_url)</p>
		</div>
	</body>
</html>

e-store/app/views/products/search.html.erb
<% if @products.empty? %>
  <p id="error">Sorry no products were found.</p>
<% end %>
<%= render @products %>

e-store/app/views/products/show.html.erb
<p id="notice"><%= notice %></p>
<!--
<p>
  <b>Item:</b>
  <%= @product.item %>
</p>

<p>
  <b><%= @product.name %></b>
  <%= image_tag(@product.image, :size => "70x100") %>
  <b>Price: </b><%= @product.price %>
  <b> Stock: </b><%= @product.stock_quantity %>
  <% if @product.sale_price > 0 then %>
      <b>*SALE* Save: <%= @product.sale_price %></b>
    <% end %>
  <br/>
  <%= @product.description %> <br/>  
</p>
-->
<%= render @product %>
<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>