e-store/config/routes.rb
EStore::Application.routes.draw do

  

  get "login/register"

  post "login/create"

  post "login/validate_user"

  get "login/show_all"

  delete "login/delete"
  
  match "/login" => 'login#index'

  resources :provences


  resources :products


  resources :orders


  resources :lineitems


  resources :customers


  root :to => "products#index"
  
#  match "admin" => "active_admin/devise/sessions#new",:as => "admin"
  
  match "result" => "products#search", :as => "result", :via => :post
  
  match "add_product_to_cart" => "products#add_product_to_cart", :as => "add_product_to_cart", :via => :post
  
  match "remove_product_to_cart" => "products#remove_product_to_cart", :as => "remove_product_to_cart", :via => :post
  
  match "checkout" => "products#checkout", :as => "checkout", :via => :post
 # match "checkout" => "products#clear_cart", :as => "clear_cart", :via => :post
 
 # match "purchase" => "products#purchase", :as => "purchase", :via => :post
  match "purchase" => "products#purchase", :as => "purchase", :via => :get
  match "customers" => "customers#new", :as => "customers", :via => :get
  
  #match "customers/:id" => "products#purchase", :as => "purchase", :via => :get
  #match "customers" => "products#purchase", :as => "purchase", :via => :get
  
  
 # match "/customer" => "customers#index"
 # match "/order" => "orders#index"
 # match "/product" => "products"

devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
end

e-store/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>EStore</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <p style="color: green"><%= flash[:notice] %></p>
  <p style="color: red"><%= flash[:error] %></p>
  <div class="banner">
    
  </div>
  <div class="nav">
    <ul>
      <li><%= link_to 'Customers', customers_path %></li> 
      <li><%= link_to 'Orders', orders_path %></li>
      <li><%= link_to 'Provences', provences_path %></li>
      <li><li><%= link_to 'Admin', admin_user_session_path %></li></li>
      <li>
        <%= link_to 'Products', products_path, :id => "product_link"%>
      </li>
      <li id="search">
        <%= form_tag result_path, :method => 'post' do %>
          <%= text_field_tag(:keyword, value = nil,
                             options = {:placeholder => "Search for products",
                                        :class => "search_box"})%>
          <%= submit_tag "Search", :class => "search_btn" %>
        <% end %>
      </li>
    </ul>
  </div>
  <div class="float_right">
    <div id="side_cart">
      <h1>Cart</h1>
      <% session[:cart].reverse.each do |cart|%>
        <%= form_tag remove_product_to_cart_path, :method => 'post' do %>
        <% @product = Product.where(:id => "#{cart.itemNo}").first %>
        <div id="cart_items">
          <span class="product-icon_mini"><%= image_tag(@product.image, :size => "35x50") %></span>
            <p><b><%= @product.name %></b><br/>
            <%= cart.itemQty %> @ <%= @product.price - @product.sale_price %>/ea.<br/>
            Sub total: $<%= ((@product.price - @product.sale_price) * cart.itemQty.to_i) %><br/>
            <%= submit_tag "Remove", :class => "remove_btn" %></p>
            <%= hidden_field_tag(:id, @product.id.to_s) %>
          <% end %>
        </div>
      <% end %>
    </div>
    <div id="side_checkout">
      <h1>Checkout</h1>
      <%= form_tag checkout_path, :method => 'post' do %>
        <%= submit_tag "Check Out!", :class => "checkout_btn" %>
        <%= submit_tag "Clear Cart!", :class => "clear_cart_btn" %>
      <% end %>
    </div>
  </div>
  <%= yield %>
  <footer>By Derek Ranger</footer>
</body>
</html>