e-store/config/routes.rb
EStore::Application.routes.draw do

  

  get "login/register"

  post "login/create"

  post "login/validate_user"

  get "login/show_all"

  delete "login/delete"
  
  match "/login" => 'login#index'

  resources :provences


  resources :products


  resources :orders


  resources :lineitems


  resources :customers


  root :to => "products#index"
  
#  match "admin" => "active_admin/devise/sessions#new",:as => "admin"
  
  match "result" => "products#search", :as => "result", :via => :post
  
  match "add_product_to_cart" => "products#add_product_to_cart", :as => "add_product_to_cart", :via => :post
  
  match "remove_product_to_cart" => "products#remove_product_to_cart", :as => "remove_product_to_cart", :via => :post
  
  match "checkout" => "products#checkout", :as => "checkout", :via => :post
 # match "checkout" => "products#clear_cart", :as => "clear_cart", :via => :post
 
 # match "purchase" => "products#purchase", :as => "purchase", :via => :post
  match "purchase" => "products#purchase", :as => "purchase", :via => :get
  match "customers" => "customers#new", :as => "customers", :via => :get
  
  #match "customers/:id" => "products#purchase", :as => "purchase", :via => :get
  #match "customers" => "products#purchase", :as => "purchase", :via => :get
  
  
 # match "/customer" => "customers#index"
 # match "/order" => "orders#index"
 # match "/product" => "products"

devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
end

e-store/app/models/lineitem.rb
class Lineitem < ActiveRecord::Base
  attr_accessible :order_id, :price, :product_id, :quantity, :sale_price
  
 # validates :order_id, :product_id, :quantity, :price, :presence => true
  # validates :price, :quantity, :numericality => { :greater_than_or_equal_to => 0 }
  
  belongs_to :order
  belongs_to :product
end

e-store/app/controllers/lineitems_controller.rb
class LineitemsController < ApplicationController
  # GET /lineitems
  # GET /lineitems.json
  def index
    @lineitems = Lineitem.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @lineitems }
    end
  end

  # GET /lineitems/1
  # GET /lineitems/1.json
  def show
    @lineitem = Lineitem.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @lineitem }
    end
  end

  # GET /lineitems/new
  # GET /lineitems/new.json
  def new
    @lineitem = Lineitem.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @lineitem }
    end
  end

  # GET /lineitems/1/edit
  def edit
    @lineitem = Lineitem.find(params[:id])
  end

  # POST /lineitems
  # POST /lineitems.json
  def create
    @lineitem = Lineitem.new(params[:lineitem])

    respond_to do |format|
      if @lineitem.save
        format.html { redirect_to @lineitem, notice: 'Lineitem was successfully created.' }
        format.json { render json: @lineitem, status: :created, location: @lineitem }
      else
        format.html { render action: "new" }
        format.json { render json: @lineitem.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /lineitems/1
  # PUT /lineitems/1.json
  def update
    @lineitem = Lineitem.find(params[:id])

    respond_to do |format|
      if @lineitem.update_attributes(params[:lineitem])
        format.html { redirect_to @lineitem, notice: 'Lineitem was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @lineitem.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lineitems/1
  # DELETE /lineitems/1.json
  def destroy
    @lineitem = Lineitem.find(params[:id])
    @lineitem.destroy

    respond_to do |format|
      format.html { redirect_to lineitems_url }
      format.json { head :no_content }
    end
  end
end

e-store/app/helpers/lineitems_helper.rb
module LineitemsHelper
end

e-store/app/views/lineitems/_form.html.erb
<%= form_for(@lineitem) do |f| %>
  <% if @lineitem.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@lineitem.errors.count, "error") %> prohibited this lineitem from being saved:</h2>

      <ul>
      <% @lineitem.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :quantity %><br />
    <%= f.number_field :quantity %>
  </div>
  <div class="field">
    <%= f.label :price %><br />
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :product_id %><br />
    <%= f.number_field :product_id %>
  </div>
  <div class="field">
    <%= f.label :order_id %><br />
    <%= f.number_field :order_id %>
  </div>
  <div class="field">
    <%= f.label :sale_price %><br />
    <%= f.text_field :sale_price %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

e-store/app/views/lineitems/edit.html.erb
<h1>Editing lineitem</h1>

<%= render 'form' %>

<%= link_to 'Show', @lineitem %> |
<%= link_to 'Back', lineitems_path %>

e-store/app/views/lineitems/index.html.erb
<h1>Listing lineitems</h1>

<table>
  <tr>
    <th>Quantity</th>
    <th>Price</th>
    <th>Product</th>
    <th>Order</th>
    <th>Sale price</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @lineitems.each do |lineitem| %>
  <tr>
    <td><%= lineitem.quantity %></td>
    <td><%= lineitem.price %></td>
    <td><%= lineitem.product_id %></td>
    <td><%= lineitem.order_id %></td>
    <td><%= lineitem.sale_price %></td>
    <td><%= link_to 'Show', lineitem %></td>
    <td><%= link_to 'Edit', edit_lineitem_path(lineitem) %></td>
    <td><%= link_to 'Destroy', lineitem, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Lineitem', new_lineitem_path %>

e-store/app/views/lineitems/new.html.erb
<h1>New lineitem</h1>

<%= render 'form' %>

<%= link_to 'Back', lineitems_path %>

e-store/app/views/lineitems/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Quantity:</b>
  <%= @lineitem.quantity %>
</p>

<p>
  <b>Price:</b>
  <%= @lineitem.price %>
</p>

<p>
  <b>Product:</b>
  <%= @lineitem.product_id %>
</p>

<p>
  <b>Order:</b>
  <%= @lineitem.order_id %>
</p>

<p>
  <b>Sale price:</b>
  <%= @lineitem.sale_price %>
</p>


<%= link_to 'Edit', edit_lineitem_path(@lineitem) %> |
<%= link_to 'Back', lineitems_path %>